schema = 3

[mod]
  [mod.'github.com/amarbel-llc/bob/packages/tap-dancer/go']
    version = 'v0.1.0'
    hash = 'sha256-pC95VLeYUZwmcosmo2mtzh1Ggk7N9rlUtXPmf7eGDpE='
    goVersion = '1.26'

  [mod.'github.com/amarbel-llc/purse-first/libs/go-mcp']
    version = 'v0.0.5'
    hash = 'sha256-M8TkhFZsfQSiLbz+Ml4L/zQ/diGptX19IUiGjSv0Vh4='
    goVersion = '1.26'

  [mod.'github.com/pelletier/go-toml/v2']
    version = 'v2.3.0'
    hash = 'sha256-3ftKBqSwUp5rs10NigReAJ8RxfnP4Aol45EkP0XRaa4='
    goVersion = '1.21.0'

  [mod.'golang.org/x/sys']
    version = 'v0.33.0'
    hash = 'sha256-wlOzIOUgAiGAtdzhW/KPl/yUVSH/lvFZfs5XOuJ9LOQ='
    goVersion = '1.23.0'

  [mod.'golang.org/x/term']
    version = 'v0.32.0'
    hash = 'sha256-4cM/vhb8EUrlfHidBRfjYEQlUQehXiydJN77YkQvAic='
    goVersion = '1.23.0'

  [mod.'golang.org/x/text']
    version = 'v0.35.0'
    hash = 'sha256-MXhEl0aLAyS+4SjQZMipoYKgNEOWdIYnr8h7WtLdTdQ='

  [mod.'mvdan.cc/sh/v3']
    version = 'v3.12.0'
    hash = 'sha256-1T55DgxWYDG1Y3SyZYLmSdLQPMVC6LUp1yLH98wKhGk='
